### ISSUE TITLE
`run.sh` only opens up 1 address

### ISSUE THREAD

**Issue by Shatnerz** [NebulousLabs/docker-sia-ant-farm#6]
Currently `run.sh` is only opening up one static address. There are use cases where someone may want to reach more than one Ant. You should consider someway to make this configurable. Perhaps reading envs or reading another config, mapping the ports.

**Comment by firyx** [comment]
You can now publish more (or all) Ants' HTTP API ports.
Implemented in `v1.0.5` by PR #10.
